- README.md
Warn users about potential stuff like this:
<pre>$ ./master focal qthardmon 01.04.00
X11 forwarding request failed on channel 0
Searching for reverse dependencies...
Verifying versions...
Sorting package list...
The following packages will be built (in that order):
qthardmon 01.04.00
Do you want to proceed with configuring and building the packages in the given versions (y/N)? y
[sudo] password for huesmann: 
We have root rights now.
<font color="#3465A4"><b>Configuring qthardmon in version 01.04.00 for focal...</b></font>
gpgv: Signature made Tue Jul 20 06:38:46 2021 CEST
W: /root/.pbuilderrc does not exist0E60CA794E76CE0E
<font color="#C4A000"><b>W: cgroups are not available on the host, not using them.</b></font>
I: Distribution is focal.
I: Current time: Tue Jul 20 17:42:57 CEST 2021 …
> Add caveat about non-standard distros

- findReverseDependencies
- master
If `doocspkgs.desy.de` is not accessible (e.g. when outside of DESY network), the script prints out a rather vague error message (see below) and tries to proceed building the package, eventually failing on missing dependencies.
This patch improves the user experience by aborting early and printing out a meaningful error message if download/creation of `Packages.DESY` fails.
<pre>$ ./master focal qthardmon 01.04.00                            
Searching for reverse dependencies...
Traceback (most recent call last):
File &quot;./findReverseDependencies&quot;, line 86, in &lt;module&gt;
main()
File &quot;./findReverseDependencies&quot;, line 69, in main
PackageFile = debian.debian_support.PackageFile(&quot;Packages.DESY&quot;)
File &quot;/usr/lib/python3/dist-packages/debian/debian_support.py& …
> Fail gracefully if doocspkgs.desy.de is not accessible

- configureRelease
- master
So far the version comparison fails for patch versions greater 9, e.g.
```
(Pdb) print(PackageAsDictionary["Version"] > dependency_versions[dependency])
True
(Pdb) print(PackageAsDictionary["Version"])
00.09focal5.01-0
(Pdb) print(dependency_versions[dependency])
00.09focal11.03-0
```
Fixed by using `packaging.version` Python module to parse the version number. I also added a check to the master script to check if `packaging` is available.
> Fix version comparison.

- makeDebianPackage
It seems to be unsupported on gitolite over http.
> revert use of git shallow clone

- config.sh
- updatePBuilder
When calling the master script at some point the additional mirrors (including security repos) are added together with the doocs repository. At this point the update of apt fails because the public desy repository requires a newer version of ca-certificates. The version installed so far from `deb http://archive.ubuntu.com/ubuntu/ focal main universe` is too old.
Now the security repos are added right from the beginning together with `ca-certificates` and related packages. Thus an up to date version of  `ca-certificates` is installed and later an update of apt including the desy repository is successful.
> Add security repos right from the beginning.

- commitDebianBuildVersions
- master
This fixes issues when git is configured to rebase pulls by
default (instead of merging).
> fix: force git pulls without rebase

- master
special case: packages depending on meta-package chimeratk-deviceaccess must also be rebuilt automatically
> build more reverse-deps of DeviceAccess

- checkPackageConsistency
- configureRelease
- templates/detect_libdir.sh
- templates/package-dev-alien.install
- templates/package-dev-headeronly.install
- templates/package-dev-noheader-dynload.install
- templates/package-dev-noheader.install
- templates/package-dev.install
- templates/package-doc.install
- templates/package-dynload.install
- templates/package-olddev.install
- templates/rules
has been tested to work with cppext 1.05 and DeviceAccess 1.09 (both not yet tagged officially), plus latest of automatically detected reverse-dependencies (those are pre-cmake-modernize versions)
> Fix detect libdir

- templates/detect_libdir.sh
in that case, no need to sort files into different packages, and detect_libdir.sh should do nothing
> handle single-package case correctly

- configureRelease
This is currently not implemented and the package just gets ignored, but since there is no use case for now the implementation is postponed.
> feat: warn if virtual package with version as dependency

- templates/control.dev-noheader-dynload
Otherwise an update of the dev package will not pull in the new symlink
package but will be happy with the currently installed and most likekly
incompatible .so symlink from the old package
> fix: Dev package depends on exact version of link

- config.sh
- updatePBuilder
Otherwise pbuilder will try to bootstrap the image from the ubuntu
repository which fails obviously
> fix: Force Debian if codename is from Debian

- configureRelease
This is used in the chimeraTK-epics package to realise a install pattern
consiting of multiple lines.
> feat: multiline values in CONFIG files

- master
This is needed to build certain Python packages which do not come with
a CMakeLists.txt, like python3-textual
> feat: require an installed dh-python3

- master
Just makes it nicer to not fail later on with command not found, though
it should be obvious
> chore: Also check for pbuilder

- pbuilder-hooks/H10update
Not sure why this is necessary, but otherwise the verification step
cannot install anything.
> fix: Add a hook that calls apt update

- configureRelease
Clear the package lists so no packages, repositories or package versions from other distributions are accidentally picked up.
> fix: picking up packages from other distros

- updatePBuilder
Also fixed most shellcheck warnings, some of them actually seemt to
prevent it from working with the --setup option resp. without an
existing image.
> fix: running updatePBuilder stand-alone

- configureRelease
- findReverseDependencies
- util.py
- Properly remove Packages.*
- Actually download the package files from the security servers, not updates
- Download security packages for Debian
- Download and unpack internally to cut down on shelling out
> fix: Fix leaking Ubuntu packages into Debian build

- util.py
downloadAndUnpack as used by findReverseDependencies produced info
messages to stdout which ended up in the master command line generated
by runMasterForDependencies. The output is now directed to stderr to
prevent this.
> fix: runMasterForDependencies spoiled by output
